#!/bin/bash
set -e

# make sure OpenHIM service is started
sleep 10

cd /usr/share/openhim-mediator-timr-vims-tz
npm install
chown -R openhim:openhim /usr/share/openhim-mediator-timr-vims-tz

service openhim-mediator-timr-vims-tz start || true
